#pragma kernel MagneticFOV

RWTexture2D<float4> Result;
Texture2D<float4> ObstacleMap;

float2 _Center;
float _Range;
float _StepSize;
int _MaxSteps;

[numthreads(8,8,1)]
void MagneticFOV(uint3 id : SV_DispatchThreadID)
{
    int2 pixel = int2(id.xy);
    float2 worldPos = pixel;
    
    float2 dir = normalize(worldPos - _Center);
    float2 pos = _Center;
    float dist = 0;
    
    [loop]
    for (int i = 0; i < _MaxSteps; i++)
    {
        pos += dir * _StepSize;
        
        dist += _StepSize;
        //float dist = distance(pos, _Center);
        if (dist > _Range)
            break;
        
        int2 texPos = int2(pos);
        if (texPos.x < 0 || texPos.x >= 256 || texPos.y < 0 || texPos.y >= 256)
            break;
        
        if (ObstacleMap.Load(int3(texPos, 0)).r > 0.5)
            break;
    }
    
    Result[pixel] = (dist <= _Range) ? float4(1, 1, 1, 0.5) : float4(0, 0, 0, 0.1);
    
    if (abs(pixel.x - _Center.x) < 2 && abs(pixel.y - _Center.y) < 2)
    {
        Result[pixel] = float4(1, 0, 0, 1); // 🔴 중앙 표시
    }
}
